<?php

namespace Necronru\PaytureBundle\Repository;

/**
 * PaytureOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaytureOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
