<?php

namespace Necronru\PaytureBundle\Repository;

/**
 * PaytureUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaytureUserRepository extends \Doctrine\ORM\EntityRepository
{
}
