parameters:
    payture_api: https://sandbox2.payture.com/
    payture_id: 'Merchant'
    payture_password: '123'

services:
    payture.client:
        class: GuzzleHttp\Client
        arguments:
          - { base_uri: "%payture_api%" }

    payture.ewallet:
        class: Necronru\Payture\EWallet\EWallet
        public: false
        arguments:
          - "@payture.client"
          - "%payture_id%"
          - "%payture_password%"

    payture.ewallet_service:
          class: Necronru\PaytureBundle\Service\EWalletService
          arguments: ["@payture.ewallet", "@doctrine.orm.entity_manager"]

